# Generated by Django 6.1.1 on 2026-09-03 02:54

import django.db.models.deletion
import ranking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Họ tên')),
                ('nickname', models.CharField(blank=True, max_length=100, verbose_name='Biệt danh')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=ranking.models.player_photo_path, verbose_name='Ảnh VĐV')),
                ('rating', models.IntegerField(default=1000, verbose_name='Điểm rating')),
                ('join_date', models.DateField(auto_now_add=True, verbose_name='Ngày tham gia CLB')),
            ],
            options={
                'verbose_name': 'Vận động viên',
                'verbose_name_plural': 'Vận động viên',
                'ordering': ['-rating'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên giải')),
                ('type', models.CharField(choices=[('khong_chap', 'Không chấp điểm'), ('co_chap', 'Có chấp điểm')], default='khong_chap', max_length=20, verbose_name='Loại giải')),
                ('date', models.DateField(verbose_name='Ngày tổ chức')),
                ('status', models.CharField(choices=[('dang_dien_ra', 'Đang diễn ra'), ('da_ket_thuc', 'Đã kết thúc')], default='dang_dien_ra', max_length=20, verbose_name='Trạng thái')),
            ],
            options={
                'verbose_name': 'Giải đấu',
                'verbose_name_plural': 'Giải đấu',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PointHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ngày')),
                ('before', models.IntegerField(verbose_name='Điểm trước')),
                ('after', models.IntegerField(verbose_name='Điểm sau')),
                ('delta', models.IntegerField(verbose_name='Thay đổi')),
                ('reason', models.CharField(max_length=255, verbose_name='Lý do')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='ranking.player', verbose_name='Vận động viên')),
            ],
            options={
                'verbose_name': 'Lịch sử điểm',
                'verbose_name_plural': 'Lịch sử điểm',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('khong_chap', 'Không chấp điểm'), ('co_chap', 'Có chấp điểm'), ('giao_huu', 'Giao hữu')], max_length=20, verbose_name='Loại trận')),
                ('sets_a', models.PositiveIntegerField(verbose_name='Số ván thắng A')),
                ('sets_b', models.PositiveIntegerField(verbose_name='Số ván thắng B')),
                ('delta_a', models.IntegerField(verbose_name='Thay đổi điểm A')),
                ('delta_b', models.IntegerField(verbose_name='Thay đổi điểm B')),
                ('date', models.DateField(verbose_name='Ngày diễn ra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_a', to='ranking.player', verbose_name='VĐV A')),
                ('player_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_b', to='ranking.player', verbose_name='VĐV B')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_won', to='ranking.player', verbose_name='Người thắng')),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='ranking.tournament', verbose_name='Giải đấu')),
            ],
            options={
                'verbose_name': 'Trận đấu',
                'verbose_name_plural': 'Trận đấu',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TournamentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.CharField(choices=[('vo_dich', 'Vô địch'), ('a_quan', 'Á quân'), ('hang_ba', 'Hạng Ba'), ('tu_ket', 'Tứ kết')], max_length=20, verbose_name='Thành tích')),
                ('bonus', models.IntegerField(verbose_name='Điểm thưởng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='ranking.player', verbose_name='Vận động viên')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='ranking.tournament', verbose_name='Giải đấu')),
            ],
            options={
                'verbose_name': 'Thành tích giải đấu',
                'verbose_name_plural': 'Thành tích giải đấu',
            },
        ),
    ]
