# Generated by Django 6.1.1 on 2026-09-07 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='winner',
        ),
        migrations.AddField(
            model_name='match',
            name='mode',
            field=models.CharField(choices=[('don', 'Đánh đơn'), ('doi', 'Đánh đôi')], default='don', max_length=10, verbose_name='Thể thức'),
        ),
        migrations.AddField(
            model_name='match',
            name='player_a2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_a2', to='ranking.player', verbose_name='VĐV A2 (đôi)'),
        ),
        migrations.AddField(
            model_name='match',
            name='player_b2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_b2', to='ranking.player', verbose_name='VĐV B2 (đôi)'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner_side',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=1, verbose_name='Bên thắng'),
        ),
        migrations.AddField(
            model_name='player',
            name='birth_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Năm sinh'),
        ),
        migrations.AddField(
            model_name='player',
            name='id_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='CCCD'),
        ),
        migrations.AddField(
            model_name='pointhistory',
            name='is_doubles',
            field=models.BooleanField(default=False, verbose_name='Trận đôi'),
        ),
        migrations.AddField(
            model_name='pointhistory',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='ranking.match', verbose_name='Trận đấu liên quan'),
        ),
        migrations.AddField(
            model_name='pointhistory',
            name='match_result',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Thắng/Thua'),
        ),
        migrations.AddField(
            model_name='pointhistory',
            name='match_score',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Tỷ số'),
        ),
    ]
