# Generated by Django 6.1.1 on 2026-09-22 02:40

import django.db.models.deletion
import ranking.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0003_match_status_pointhistory_result_alter_match_delta_a_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=ranking.models.player_photo_path, validators=[ranking.models.validate_photo_size], verbose_name='Ảnh VĐV'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_account', to='ranking.player', verbose_name='Vận động viên gắn với')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Hồ sơ tài khoản',
                'verbose_name_plural': 'Hồ sơ tài khoản',
            },
        ),
    ]
