# Generated by Django 6.1.1 on 2026-09-23 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0004_alter_player_photo_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Tên đăng nhập')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='Số lần sai liên tiếp')),
                ('captcha_question', models.CharField(blank=True, default='', max_length=20, verbose_name='Câu hỏi CAPTCHA hiện tại')),
                ('captcha_answer', models.CharField(blank=True, default='', max_length=10, verbose_name='Đáp án CAPTCHA hiện tại')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Lần cập nhật gần nhất')),
            ],
            options={
                'verbose_name': 'Lượt đăng nhập sai',
                'verbose_name_plural': 'Lượt đăng nhập sai',
            },
        ),
    ]
