# Generated by Django 6.1.1 on 2026-09-23 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0005_loginattempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginattempt',
            name='captcha_answer',
        ),
        migrations.RemoveField(
            model_name='loginattempt',
            name='captcha_question',
        ),
    ]
