# Generated by Django 6.1.1 on 2026-09-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0006_remove_loginattempt_captcha_answer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournamentresult',
            options={'ordering': ['-created_at'], 'verbose_name': 'Thành tích giải đấu', 'verbose_name_plural': 'Thành tích giải đấu'},
        ),
        migrations.AddField(
            model_name='tournamentresult',
            name='bonus_applied',
            field=models.BooleanField(default=True, verbose_name='Đã cộng điểm cho VĐV'),
        ),
        migrations.AddField(
            model_name='tournamentresult',
            name='content_type',
            field=models.CharField(choices=[('don', 'Đơn'), ('doi', 'Đôi'), ('dong_doi', 'Đồng đội')], default='don', max_length=10, verbose_name='Nội dung'),
        ),
        migrations.AddField(
            model_name='tournamentresult',
            name='teammates',
            field=models.ManyToManyField(blank=True, related_name='results_as_teammate', to='ranking.player', verbose_name='Đồng đội (Đôi/Đồng đội)'),
        ),
        migrations.AlterField(
            model_name='tournamentresult',
            name='bonus',
            field=models.IntegerField(default=0, verbose_name='Điểm thưởng (mỗi người)'),
        ),
    ]
