# Generated by Django 6.1.1 on 2026-09-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0007_alter_tournamentresult_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k_khong_chap', models.PositiveIntegerField(default=32, verbose_name='Hệ số K — Giải Không chấp điểm')),
                ('k_co_chap', models.PositiveIntegerField(default=20, verbose_name='Hệ số K — Giải Có chấp điểm')),
                ('k_giao_huu', models.PositiveIntegerField(default=10, verbose_name='Hệ số K — Giao hữu')),
                ('bonus_vo_dich', models.PositiveIntegerField(default=50, verbose_name='Điểm thưởng gốc — Vô địch')),
                ('bonus_a_quan', models.PositiveIntegerField(default=30, verbose_name='Điểm thưởng gốc — Á quân')),
                ('bonus_hang_ba', models.PositiveIntegerField(default=20, verbose_name='Điểm thưởng gốc — Hạng Ba')),
                ('bonus_tu_ket', models.PositiveIntegerField(default=10, verbose_name='Điểm thưởng gốc — Tứ kết')),
                ('mult_khong_chap', models.FloatField(default=1.6, verbose_name='Hệ số nhân thưởng — Không chấp điểm')),
                ('mult_co_chap', models.FloatField(default=1.0, verbose_name='Hệ số nhân thưởng — Có chấp điểm')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
            ],
            options={
                'verbose_name': 'Cấu hình tính điểm',
                'verbose_name_plural': 'Cấu hình tính điểm',
            },
        ),
    ]
