# Generated by Django 6.1.1 on 2026-10-05 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0008_rankingconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='stage',
            field=models.CharField(blank=True, choices=[('bang', 'Vòng bảng'), ('vong_1_8', 'Vòng 1/8'), ('tu_ket', 'Tứ kết'), ('ban_ket', 'Bán kết'), ('tranh_hang_ba', 'Tranh hạng Ba'), ('chung_ket', 'Chung kết')], default='', max_length=20, verbose_name='Giai đoạn'),
        ),
        migrations.CreateModel(
            name='TournamentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Tên bảng')),
                ('players', models.ManyToManyField(blank=True, related_name='tournament_groups', to='ranking.player', verbose_name='VĐV trong bảng')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='ranking.tournament', verbose_name='Giải đấu')),
            ],
            options={
                'verbose_name': 'Bảng đấu',
                'verbose_name_plural': 'Bảng đấu',
                'ordering': ['name'],
                'unique_together': {('tournament', 'name')},
            },
        ),
        migrations.AddField(
            model_name='match',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='ranking.tournamentgroup', verbose_name='Bảng đấu'),
        ),
    ]
